module "kube-1" {
  source         = "./modules/vm"
  vm_name        = "kube-1"
  tags           = ["kubernetes"]
  mac_address  = "BC:24:11:62:C1:00"
  vlan_id      = 10
  vm_id        = 100
  processor_cores        = 3
  processor_type         = "host"
  datastore_id      = "fast-local-lvm"
  disk_gb              = 64
  memory_mb = 8192
}
module "kube-2" {
  source         = "./modules/vm"
  vm_name        = "kube-2"
  tags           = ["kubernetes"]
  mac_address  = "BC:24:11:62:C1:17"
  vlan_id      = 10
  vm_id        = 117
  processor_cores        = 3
  processor_type         = "host"
  datastore_id      = "fast-local-lvm"
  disk_gb              = 64
  memory_mb = 8192
}
module "kube-3" {
  source         = "./modules/vm"
  vm_name        = "kube-3"
  tags           = ["kubernetes"]
  mac_address  = "BC:24:11:62:C1:18"
  vlan_id      = 10
  vm_id        = 118
  processor_cores        = 3
  processor_type         = "host"
  datastore_id      = "fast-local-lvm"
  disk_gb              = 64
  memory_mb = 8192
}
